import assert from "node:assert/strict";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { graphql, getIntrospectionQuery } from "graphql";
import prettier from "prettier";
import {
  compileSchema,
  createSchemaIR,
  generateViewQLSchema,
  loadSchema,
  loadSchemaFile,
} from "../dist/index.js";

const SDL = `
  scalar DateTime @specifiedBy(url: "https://example.test/date-time")
  enum Role { ADMIN USER @deprecated(reason: "legacy") }
  interface Node { id: ID! }
  interface Named implements Node { id: ID!, name: String! }
  type User implements Node & Named { id: ID!, name: String!, friends: [User] }
  union SearchResult = User
  input Filter { term: String, limit: Int! = 10 }
  input Selector @oneOf { id: ID, name: String }
  type Query { user(id: ID!, filter: Filter): User, search: [SearchResult!]! }
`;

function formatTypeScript(source) {
  return prettier.format(source, {
    parser: "typescript",
    endOfLine: "lf",
    printWidth: 80,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  });
}

test("normalizes SDL into a source-independent schema IR", async () => {
  const schema = await loadSchema({ kind: "sdl", sdl: SDL });
  const ir = createSchemaIR(schema);
  const named = ir.types.find((type) => type.name === "Named");
  const query = ir.types.find((type) => type.name === "Query");

  assert.deepEqual(named.interfaces, ["Node"]);
  assert.equal(query.rootKind, "query");
  assert.equal(query.fields[0].args[0].type.kind, "nonNull");
});

test("emits spec-backed facade types with exact nullability and inputs", async () => {
  const output = await compileSchema(
    { kind: "sdl", sdl: SDL },
    { scalarMappings: { DateTime: "string" } },
  );

  const expected = `
    // Generated by @viewql/schema. Do not edit.

    import * as GraphQLSpec from "@viewql/spec";

    export type DateTime = string;

    export type Filter = {
      readonly term?: GraphQLSpec.String | null;
      readonly limit?: GraphQLSpec.Int;
    };

    export interface Named extends Node, GraphQLSpec.Interface {
      id(): GraphQLSpec.ID;
      name(): GraphQLSpec.String;
    }

    export declare const Named: GraphQLSpec.GraphQLType<Named>;

    export interface Node extends GraphQLSpec.Interface {
      id(): GraphQLSpec.ID;
    }

    export declare const Node: GraphQLSpec.GraphQLType<Node>;

    export interface Query extends GraphQLSpec.Query {
      user(args: {
        readonly id: GraphQLSpec.ID;
        readonly filter?: Filter | null;
      }): User | null;
      search(): ReadonlyArray<SearchResult>;
    }

    export declare const Query: GraphQLSpec.GraphQLType<Query>;

    export type Role = "ADMIN" | "USER";

    export type SearchResult = User;

    export declare const SearchResult: GraphQLSpec.GraphQLType<SearchResult>;

    export type Selector =
      | {
          readonly id: GraphQLSpec.ID;
          readonly name?: never;
        }
      | {
          readonly id?: never;
          readonly name: GraphQLSpec.String;
        };

    export interface User extends Node, Named, GraphQLSpec.Obj {
      id(): GraphQLSpec.ID;
      name(): GraphQLSpec.String;
      friends(): ReadonlyArray<User | null> | null;
    }

    export declare const User: GraphQLSpec.GraphQLType<User>;
  `;

  assert.equal(await formatTypeScript(output), await formatTypeScript(expected));
});

test("loads local SDL and introspection JSON through the same boundary", async () => {
  const directory = await mkdtemp(join(tmpdir(), "viewql-schema-"));
  const sdlPath = join(directory, "schema.graphql");
  const jsonPath = join(directory, "schema.json");
  await writeFile(sdlPath, SDL);

  const serverSchema = await loadSchemaFile(sdlPath);
  const result = await graphql({ schema: serverSchema, source: getIntrospectionQuery({ oneOf: true }) });
  await writeFile(jsonPath, JSON.stringify(result));
  const clientSchema = await loadSchemaFile(jsonPath);

  assert.equal(generateViewQLSchema(clientSchema), generateViewQLSchema(serverSchema));
});

test("rejects malformed introspection input and missing scalar mappings when requested", async () => {
  await assert.rejects(
    loadSchema({ kind: "introspection", result: { data: {} } }),
    /data\.__schema or __schema/,
  );
  const schema = await loadSchema({ kind: "sdl", sdl: "scalar Secret\ntype Query { secret: Secret }" });
  assert.throws(
    () => generateViewQLSchema(schema, { unmappedCustomScalar: "error" }),
    /Custom scalar Secret has no TypeScript mapping/,
  );
});
