import assert from "node:assert/strict";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { graphql, getIntrospectionQuery } from "graphql";
import prettier from "prettier";
import ts from "typescript";
import {
  compileSchema,
  generateViewQLSchema,
  loadSchema,
  loadSchemaFile,
} from "../dist/index.js";

const SDL = `
  type Account implements Node { id: ID! }
  scalar DateTime @specifiedBy(url: "https://example.test/date-time")
  input Filter { limit: Int! = 10, term: String }
  interface Named implements Node { id: ID!, name: String! }
  interface Node { id: ID! }
  type Query { search: [SearchResult!]!, user(filter: Filter, id: ID!): User }
  enum Role { ADMIN USER @deprecated(reason: "legacy") }
  union SearchResult = Account | User
  input Selector @oneOf { id: ID, name: String }
  type User implements Named & Node { friends: [User], id: ID!, name: String! }
`;

const UNALPHABETIZED_SDL = `
  type User implements Node & Named { name: String!, id: ID!, friends: [User] }
  input Selector @oneOf { name: String, id: ID }
  union SearchResult = User | Account
  enum Role { USER @deprecated(reason: "legacy") ADMIN }
  type Query { user(id: ID!, filter: Filter): User, search: [SearchResult!]! }
  interface Node { id: ID! }
  interface Named implements Node { name: String!, id: ID! }
  input Filter { term: String, limit: Int! = 10 }
  scalar DateTime @specifiedBy(url: "https://example.test/date-time")
  type Account implements Node { id: ID! }
`;

function formatTypeScript(source) {
  return prettier.format(source, {
    parser: "typescript",
    endOfLine: "lf",
    printWidth: 80,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  });
}

test("emits spec-backed facade types with exact nullability and inputs", async () => {
  const output = await compileSchema(
    { kind: "sdl", sdl: SDL },
    { scalarMappings: { DateTime: "string" } },
  );

  const expected = `
    // Generated by @viewql/schema. Do not edit.

    import * as GraphQLSpec from "@viewql/spec";

    export interface Account extends GraphQLSpec.Obj {
      readonly __typename: "Account";
      id(): GraphQLSpec.ID;
    }

    export type DateTime = string;

    export type Filter = {
      readonly limit?: GraphQLSpec.Int;
      readonly term?: GraphQLSpec.String | null;
    };

    export type Named = User;

    export declare function asNamed(
      value: GraphQLSpec.Obj | null | undefined,
    ): Named | null;

    export type Node = Account | User;

    export declare function asNode(
      value: GraphQLSpec.Obj | null | undefined,
    ): Node | null;

    export interface Query extends GraphQLSpec.Query {
      readonly __typename: "Query";
      search(): ReadonlyArray<SearchResult>;
      user(args: {
        readonly filter?: Filter | null;
        readonly id: GraphQLSpec.ID;
      }): User | null;
    }

    export type Role = "ADMIN" | "USER";

    export type SearchResult = Account | User;

    export type Selector =
      | {
          readonly id: GraphQLSpec.ID;
          readonly name?: never;
        }
      | {
          readonly id?: never;
          readonly name: GraphQLSpec.String;
        };

    export interface User extends GraphQLSpec.Obj {
      readonly __typename: "User";
      friends(): ReadonlyArray<User | null> | null;
      id(): GraphQLSpec.ID;
      name(): GraphQLSpec.String;
    }

  `;

  assert.equal(await formatTypeScript(output), await formatTypeScript(expected));
});

test("alphabetizes output independently of SDL declaration order", async () => {
  const options = { scalarMappings: { DateTime: "string" } };
  const alphabetical = await compileSchema({ kind: "sdl", sdl: SDL }, options);
  const unalphabetical = await compileSchema(
    { kind: "sdl", sdl: UNALPHABETIZED_SDL },
    options,
  );

  assert.equal(unalphabetical, alphabetical);
});

test("supports TypeScript narrowing for objects, interfaces, and OneOf inputs", async () => {
  const directory = await mkdtemp(join(tmpdir(), "viewql-narrowing-"));
  const schemaPath = join(directory, "schema.ts");
  const specPath = join(directory, "graphql-spec.ts");
  const usagePath = join(directory, "usage.ts");
  const schema = await compileSchema(
    { kind: "sdl", sdl: SDL },
    {
      scalarMappings: { DateTime: "string" },
      specModule: "./graphql-spec.js",
    },
  );

  await writeFile(schemaPath, schema);
  await writeFile(
    specPath,
    `
      export type ID = string & { readonly __id: unique symbol };
      export type Int = number & { readonly __int: unique symbol };
      export type Float = number;
      export type String = string;
      export type Boolean = boolean;
      export interface Obj {}
      export interface Query extends Obj {}
    `,
  );
  await writeFile(
    usagePath,
    `
      import * as GraphQLSpec from "./graphql-spec.js";
      import * as Schema from "./schema.js";

      declare const node: Schema.Node;

      if (node.__typename === "Account") {
        const account: Schema.Account = node;
        account.id();
      } else {
        const user: Schema.User = node;
        user.name();
      }

      const named = Schema.asNamed(node);
      if (named != null) {
        named.name();
      }

      declare const selector: Schema.Selector;
      if (selector.id != null) {
        const id: GraphQLSpec.ID = selector.id;
      } else if (selector.name != null) {
        const name: GraphQLSpec.String = selector.name;
      }
    `,
  );

  const program = ts.createProgram([schemaPath, specPath, usagePath], {
    module: ts.ModuleKind.NodeNext,
    moduleResolution: ts.ModuleResolutionKind.NodeNext,
    noEmit: true,
    strict: true,
    target: ts.ScriptTarget.ES2022,
  });
  const diagnostics = ts.getPreEmitDiagnostics(program);

  assert.deepEqual(
    diagnostics.map((diagnostic) =>
      ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n"),
    ),
    [],
  );
});

test("loads local SDL and introspection JSON through the same boundary", async () => {
  const directory = await mkdtemp(join(tmpdir(), "viewql-schema-"));
  const sdlPath = join(directory, "schema.graphql");
  const jsonPath = join(directory, "schema.json");
  await writeFile(sdlPath, SDL);

  const serverSchema = await loadSchemaFile(sdlPath);
  const result = await graphql({ schema: serverSchema, source: getIntrospectionQuery({ oneOf: true }) });
  await writeFile(jsonPath, JSON.stringify(result));
  const clientSchema = await loadSchemaFile(jsonPath);

  assert.equal(generateViewQLSchema(clientSchema), generateViewQLSchema(serverSchema));
});

test("rejects malformed introspection input and missing scalar mappings when requested", async () => {
  await assert.rejects(
    loadSchema({ kind: "introspection", result: { data: {} } }),
    /data\.__schema or __schema/,
  );
  const schema = await loadSchema({ kind: "sdl", sdl: "scalar Secret\ntype Query { secret: Secret }" });
  assert.throws(
    () => generateViewQLSchema(schema, { unmappedCustomScalar: "error" }),
    /Custom scalar Secret has no TypeScript mapping/,
  );
});
