import assert from "node:assert/strict";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { graphql, getIntrospectionQuery } from "graphql";
import prettier from "prettier";
import {
  compileSchema,
  generateViewQLSchema,
  loadSchema,
  loadSchemaFile,
} from "../dist/index.js";

const SDL = `
  type Account { id: ID! }
  scalar DateTime @specifiedBy(url: "https://example.test/date-time")
  input Filter { limit: Int! = 10, term: String }
  interface Named implements Node { id: ID!, name: String! }
  interface Node { id: ID! }
  type Query { search: [SearchResult!]!, user(filter: Filter, id: ID!): User }
  enum Role { ADMIN USER @deprecated(reason: "legacy") }
  union SearchResult = Account | User
  input Selector @oneOf { id: ID, name: String }
  type User implements Named & Node { friends: [User], id: ID!, name: String! }
`;

const UNALPHABETIZED_SDL = `
  type User implements Node & Named { name: String!, id: ID!, friends: [User] }
  input Selector @oneOf { name: String, id: ID }
  union SearchResult = User | Account
  enum Role { USER @deprecated(reason: "legacy") ADMIN }
  type Query { user(id: ID!, filter: Filter): User, search: [SearchResult!]! }
  interface Node { id: ID! }
  interface Named implements Node { name: String!, id: ID! }
  input Filter { term: String, limit: Int! = 10 }
  scalar DateTime @specifiedBy(url: "https://example.test/date-time")
  type Account { id: ID! }
`;

function formatTypeScript(source) {
  return prettier.format(source, {
    parser: "typescript",
    endOfLine: "lf",
    printWidth: 80,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  });
}

test("emits spec-backed facade types with exact nullability and inputs", async () => {
  const output = await compileSchema(
    { kind: "sdl", sdl: SDL },
    { scalarMappings: { DateTime: "string" } },
  );

  const expected = `
    // Generated by @viewql/schema. Do not edit.

    import * as GraphQLSpec from "@viewql/spec";

    export interface Account extends GraphQLSpec.Obj {
      id(): GraphQLSpec.ID;
    }

    export declare const Account: GraphQLSpec.GraphQLType<Account>;

    export type DateTime = string;

    export type Filter = {
      readonly limit?: GraphQLSpec.Int;
      readonly term?: GraphQLSpec.String | null;
    };

    export interface Named extends Node, GraphQLSpec.Interface {
      id(): GraphQLSpec.ID;
      name(): GraphQLSpec.String;
    }

    export declare const Named: GraphQLSpec.GraphQLType<Named>;

    export interface Node extends GraphQLSpec.Interface {
      id(): GraphQLSpec.ID;
    }

    export declare const Node: GraphQLSpec.GraphQLType<Node>;

    export interface Query extends GraphQLSpec.Query {
      search(): ReadonlyArray<SearchResult>;
      user(args: {
        readonly filter?: Filter | null;
        readonly id: GraphQLSpec.ID;
      }): User | null;
    }

    export declare const Query: GraphQLSpec.GraphQLType<Query>;

    export type Role = "ADMIN" | "USER";

    export type SearchResult = Account | User;

    export declare const SearchResult: GraphQLSpec.GraphQLType<SearchResult>;

    export type Selector =
      | {
          readonly id: GraphQLSpec.ID;
          readonly name?: never;
        }
      | {
          readonly id?: never;
          readonly name: GraphQLSpec.String;
        };

    export interface User extends Named, Node, GraphQLSpec.Obj {
      friends(): ReadonlyArray<User | null> | null;
      id(): GraphQLSpec.ID;
      name(): GraphQLSpec.String;
    }

    export declare const User: GraphQLSpec.GraphQLType<User>;
  `;

  assert.equal(await formatTypeScript(output), await formatTypeScript(expected));
});

test("alphabetizes output independently of SDL declaration order", async () => {
  const options = { scalarMappings: { DateTime: "string" } };
  const alphabetical = await compileSchema({ kind: "sdl", sdl: SDL }, options);
  const unalphabetical = await compileSchema(
    { kind: "sdl", sdl: UNALPHABETIZED_SDL },
    options,
  );

  assert.equal(unalphabetical, alphabetical);
});

test("loads local SDL and introspection JSON through the same boundary", async () => {
  const directory = await mkdtemp(join(tmpdir(), "viewql-schema-"));
  const sdlPath = join(directory, "schema.graphql");
  const jsonPath = join(directory, "schema.json");
  await writeFile(sdlPath, SDL);

  const serverSchema = await loadSchemaFile(sdlPath);
  const result = await graphql({ schema: serverSchema, source: getIntrospectionQuery({ oneOf: true }) });
  await writeFile(jsonPath, JSON.stringify(result));
  const clientSchema = await loadSchemaFile(jsonPath);

  assert.equal(generateViewQLSchema(clientSchema), generateViewQLSchema(serverSchema));
});

test("rejects malformed introspection input and missing scalar mappings when requested", async () => {
  await assert.rejects(
    loadSchema({ kind: "introspection", result: { data: {} } }),
    /data\.__schema or __schema/,
  );
  const schema = await loadSchema({ kind: "sdl", sdl: "scalar Secret\ntype Query { secret: Secret }" });
  assert.throws(
    () => generateViewQLSchema(schema, { unmappedCustomScalar: "error" }),
    /Custom scalar Secret has no TypeScript mapping/,
  );
});
