import type { SchemaArgument, SchemaNamedType, SchemaTypeRef, ViewQLSchema } from "./ir.js";

export interface GeneratorOptions {
  readonly specModule?: string;
  readonly scalarMappings?: Readonly<Record<string, string>>;
  readonly unmappedCustomScalar?: "unknown" | "error";
  readonly header?: string | false;
}

const BUILTIN_SCALARS: Readonly<Record<string, string>> = {
  ID: "GraphQLSpec.ID", Int: "GraphQLSpec.Int", Float: "GraphQLSpec.Float",
  String: "GraphQLSpec.String", Boolean: "GraphQLSpec.Boolean",
};

function isNullable(type: SchemaTypeRef): boolean { return type.kind !== "nonNull"; }
function withoutOuterNull(type: SchemaTypeRef): SchemaTypeRef { return type.kind === "nonNull" ? type.ofType : type; }

function emitter(options: GeneratorOptions) {
  const mappings = { ...BUILTIN_SCALARS, ...options.scalarMappings };
  const named = (name: string): string => mappings[name] ?? name;
  const typeRef = (type: SchemaTypeRef, nullable = true): string => {
    if (type.kind === "nonNull") return typeRef(type.ofType, false);
    const base = type.kind === "list" ? `ReadonlyArray<${typeRef(type.ofType)}>` : named(type.name);
    return nullable ? `${base} | null` : base;
  };
  const property = (name: string): string => /^[$A-Z_a-z][$\w]*$/.test(name) ? name : JSON.stringify(name);
  const args = (values: readonly SchemaArgument[]): string => values.length === 0 ? "" : `args: {\n${values.map((arg) => `    readonly ${property(arg.name)}${isNullable(arg.type) || arg.hasDefault ? "?" : ""}: ${typeRef(arg.type)};`).join("\n")}\n  }`;
  return { named, typeRef, property, args };
}

function emitNamedType(type: SchemaNamedType, options: GeneratorOptions): string {
  const out = emitter(options);
  switch (type.kind) {
    case "scalar": {
      if (type.name in BUILTIN_SCALARS) return "";
      const mapping = options.scalarMappings?.[type.name];
      if (mapping === undefined && options.unmappedCustomScalar === "error") throw new TypeError(`Custom scalar ${type.name} has no TypeScript mapping.`);
      return `export type ${type.name} = ${mapping ?? "unknown"};`;
    }
    case "enum": return `export type ${type.name} =\n${type.values.map(({ name }) => `  | ${JSON.stringify(name)}`).join("\n")};`;
    case "union": return `export type ${type.name} = ${type.members.length === 0 ? "never" : type.members.join(" | ")};\n\nexport declare const ${type.name}: GraphQLSpec.GraphQLType<${type.name}>;`;
    case "inputObject": {
      if (type.isOneOf) {
        if (type.fields.length === 0) return `export type ${type.name} = never;`;
        const variants = type.fields.map((selected) => `  | {\n${type.fields.map((field) => field === selected
          ? `      readonly ${out.property(field.name)}: ${out.typeRef(withoutOuterNull(field.type), false)};`
          : `      readonly ${out.property(field.name)}?: never;`).join("\n")}\n    }`).join("\n");
        return `export type ${type.name} =\n${variants};`;
      }
      return `export type ${type.name} = {\n${type.fields.map((field) => `  readonly ${out.property(field.name)}${isNullable(field.type) || field.hasDefault ? "?" : ""}: ${out.typeRef(field.type)};`).join("\n")}\n};`;
    }
    case "interface": {
      const bases = [...type.interfaces, "GraphQLSpec.Interface"];
      const fields = type.fields.map((field) => `  ${out.property(field.name)}(${out.args(field.args)}): ${out.typeRef(field.type)};`).join("\n");
      return `export interface ${type.name} extends ${bases.join(", ")} {\n${fields}\n}\n\nexport declare const ${type.name}: GraphQLSpec.GraphQLType<${type.name}>;`;
    }
    case "object": {
      const marker = type.rootKind === "query" ? "GraphQLSpec.Query" : "GraphQLSpec.Obj";
      const bases = [...type.interfaces, marker];
      const fields = type.fields.map((field) => `  ${out.property(field.name)}(${out.args(field.args)}): ${out.typeRef(field.type)};`).join("\n");
      return `export interface ${type.name} extends ${bases.join(", ")} {\n${fields}\n}\n\nexport declare const ${type.name}: GraphQLSpec.GraphQLType<${type.name}>;`;
    }
  }
}

/** Deterministically emits a dependency-free (except @viewql/spec) TypeScript facade. */
export function emitViewQLSchema(ir: ViewQLSchema, options: GeneratorOptions = {}): string {
  const header = options.header === false ? "" : `${options.header ?? "// Generated by @viewql/schema. Do not edit."}\n\n`;
  const body = ir.types.map((type) => emitNamedType(type, options)).filter(Boolean).join("\n\n");
  return `${header}import * as GraphQLSpec from ${JSON.stringify(options.specModule ?? "@viewql/spec")};\n\n${body}\n`;
}
